"""add updated_at

Revision ID: 0cad0bb7499b
Revises: 20cd0620cb05
Create Date: 2024-06-23 14:42:59.500360

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0cad0bb7499b'
down_revision = '20cd0620cb05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
